package service

import (
	"bytes"
	"encoding/xml"
	"errors"
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"unicode"
)

const launchdPlistDoctype = `<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`

var launchdCanonicalElements = strings.NewReplacer(
	"<true></true>", "<true/>",
	"<false></false>", "<false/>",
)

var (
	reLaunchdProgram = regexp.MustCompile(`"Program"\s*=\s*("(?:\\.|[^"\\])*");`)
	reLaunchdArg0    = regexp.MustCompile(`"ProgramArguments"\s*=\s*\(\s*("(?:\\.|[^"\\])*")`)
	reLaunchdArgs    = regexp.MustCompile(`(?s)"ProgramArguments"\s*=\s*\((.*?)\);`)
	reQuotedArgument = regexp.MustCompile(`"(?:\\.|[^"\\])*"`)
)

func renderSystemdUnit(executable, cfgPath string, cacheSeconds int) string {
	args := []string{executable, "-config", cfgPath, "--cache", strconv.Itoa(cacheSeconds)}
	quoted := make([]string, 0, len(args))
	for _, arg := range args {
		quoted = append(quoted, quoteSystemdArgument(arg))
	}

	return `[Unit]
Description=SSH Agent Proxy (filtering proxy for ssh-agent)
After=default.target

[Service]
Type=simple
ExecStart=` + strings.Join(quoted, " ") + `
Restart=on-failure
RestartSec=2

[Install]
WantedBy=default.target
`
}

// quoteSystemdArgument applies the two substitutions performed after systemd
// parses command-line quoting, then uses systemd's supported C-style quoting.
func quoteSystemdArgument(arg string) string {
	escaped := strings.NewReplacer("%", "%%", "$", "$$").Replace(arg)
	return strconv.Quote(escaped)
}

func parseSystemdExecStartBinary(unit string) (string, error) {
	args, err := parseSystemdExecStart(unit)
	if err != nil || len(args) == 0 {
		return "", err
	}
	return args[0], nil
}

func parseSystemdExecStart(unit string) ([]string, error) {
	for _, line := range strings.Split(unit, "\n") {
		rest, ok := strings.CutPrefix(line, "ExecStart=")
		if !ok {
			continue
		}

		args, err := parseSystemdArguments(rest)
		if err != nil {
			return nil, fmt.Errorf("parsing ExecStart: %w", err)
		}
		if len(args) == 0 {
			return nil, errors.New("parsing ExecStart: command is empty")
		}
		return args, nil
	}
	return nil, nil
}

// parseSystemdArguments parses the quoted form generated by renderSystemdUnit.
// It also accepts unquoted arguments so status continues to work for units
// installed by older versions.
func parseSystemdArguments(line string) ([]string, error) {
	var args []string
	for {
		line = strings.TrimLeftFunc(line, unicode.IsSpace)
		if line == "" {
			return args, nil
		}

		if line[0] != '"' {
			end := strings.IndexFunc(line, unicode.IsSpace)
			if end < 0 {
				return append(args, line), nil
			}
			args = append(args, line[:end])
			line = line[end:]
			continue
		}

		quoted, err := strconv.QuotedPrefix(line)
		if err != nil {
			return nil, fmt.Errorf("reading quoted argument: %w", err)
		}
		value, err := strconv.Unquote(quoted)
		if err != nil {
			return nil, fmt.Errorf("unquoting argument: %w", err)
		}
		line = line[len(quoted):]
		if line != "" && !unicode.IsSpace(rune(line[0])) {
			return nil, errors.New("unexpected character after quoted argument")
		}
		args = append(args, strings.NewReplacer("%%", "%", "$$", "$").Replace(value))
	}
}

type launchdPlist struct {
	Label            string
	ProgramArguments []string
	LogPath          string
}

func renderLaunchdPlist(label string, programArguments []string, logPath string) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(xml.Header)
	buf.WriteString(launchdPlistDoctype)
	buf.WriteByte('\n')

	enc := xml.NewEncoder(&buf)
	enc.Indent("", "\t")
	if err := enc.Encode(launchdPlist{
		Label:            label,
		ProgramArguments: programArguments,
		LogPath:          logPath,
	}); err != nil {
		return nil, fmt.Errorf("encoding launchd plist: %w", err)
	}

	// encoding/xml emits empty elements using separate start/end tags. They
	// are valid XML, but launchd's property-list parser rejects expanded
	// boolean elements and requires the canonical <true/> and <false/> forms.
	return []byte(launchdCanonicalElements.Replace(buf.String())), nil
}

func (p launchdPlist) MarshalXML(enc *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "plist"
	start.Attr = []xml.Attr{{Name: xml.Name{Local: "version"}, Value: "1.0"}}
	if err := enc.EncodeToken(start); err != nil {
		return err
	}

	dict := xml.StartElement{Name: xml.Name{Local: "dict"}}
	if err := enc.EncodeToken(dict); err != nil {
		return err
	}
	if err := encodePlistString(enc, "Label", p.Label); err != nil {
		return err
	}
	if err := encodePlistStringArray(enc, "ProgramArguments", p.ProgramArguments); err != nil {
		return err
	}
	if err := encodePlistBool(enc, "RunAtLoad", true); err != nil {
		return err
	}
	if err := encodePlistBoolDict(enc, "KeepAlive", "SuccessfulExit", false); err != nil {
		return err
	}
	if err := encodePlistString(enc, "StandardOutPath", p.LogPath); err != nil {
		return err
	}
	if err := encodePlistString(enc, "StandardErrorPath", p.LogPath); err != nil {
		return err
	}
	if err := enc.EncodeToken(dict.End()); err != nil {
		return err
	}
	return enc.EncodeToken(start.End())
}

func encodePlistKey(enc *xml.Encoder, key string) error {
	return enc.EncodeElement(key, xml.StartElement{Name: xml.Name{Local: "key"}})
}

func encodePlistString(enc *xml.Encoder, key, value string) error {
	if err := encodePlistKey(enc, key); err != nil {
		return err
	}
	return enc.EncodeElement(value, xml.StartElement{Name: xml.Name{Local: "string"}})
}

func encodePlistStringArray(enc *xml.Encoder, key string, values []string) error {
	if err := encodePlistKey(enc, key); err != nil {
		return err
	}
	array := xml.StartElement{Name: xml.Name{Local: "array"}}
	if err := enc.EncodeToken(array); err != nil {
		return err
	}
	for _, value := range values {
		if err := enc.EncodeElement(value, xml.StartElement{Name: xml.Name{Local: "string"}}); err != nil {
			return err
		}
	}
	return enc.EncodeToken(array.End())
}

func encodePlistBool(enc *xml.Encoder, key string, value bool) error {
	if err := encodePlistKey(enc, key); err != nil {
		return err
	}
	name := "false"
	if value {
		name = "true"
	}
	return enc.EncodeElement(struct{}{}, xml.StartElement{Name: xml.Name{Local: name}})
}

func encodePlistBoolDict(enc *xml.Encoder, key, childKey string, childValue bool) error {
	if err := encodePlistKey(enc, key); err != nil {
		return err
	}
	dict := xml.StartElement{Name: xml.Name{Local: "dict"}}
	if err := enc.EncodeToken(dict); err != nil {
		return err
	}
	if err := encodePlistBool(enc, childKey, childValue); err != nil {
		return err
	}
	return enc.EncodeToken(dict.End())
}

func parseLaunchdProgram(output string) (string, error) {
	for _, re := range []*regexp.Regexp{reLaunchdProgram, reLaunchdArg0} {
		match := re.FindStringSubmatch(output)
		if match == nil {
			continue
		}
		program, err := strconv.Unquote(match[1])
		if err != nil {
			return "", fmt.Errorf("unquoting launchd program: %w", err)
		}
		return program, nil
	}
	return "", nil
}

func parseLaunchdArguments(output string) ([]string, error) {
	match := reLaunchdArgs.FindStringSubmatch(output)
	if match == nil {
		return nil, nil
	}
	quoted := reQuotedArgument.FindAllString(match[1], -1)
	args := make([]string, 0, len(quoted))
	for _, value := range quoted {
		arg, err := strconv.Unquote(value)
		if err != nil {
			return nil, fmt.Errorf("unquoting launchd argument: %w", err)
		}
		args = append(args, arg)
	}
	return args, nil
}

func parseLaunchdPlistArguments(data []byte) ([]string, error) {
	var plist struct {
		Dict struct {
			ProgramArguments []string `xml:"array>string"`
		} `xml:"dict"`
	}
	if err := xml.Unmarshal(data, &plist); err != nil {
		return nil, fmt.Errorf("parsing launchd plist: %w", err)
	}
	return plist.Dict.ProgramArguments, nil
}

func configArgument(args []string) string {
	var configPath string
	for i := 1; i < len(args); i++ {
		if args[i] == "-config" || args[i] == "--config" {
			if i+1 < len(args) {
				configPath = args[i+1]
				i++
			}
			continue
		}
		for _, prefix := range []string{"-config=", "--config="} {
			if value, ok := strings.CutPrefix(args[i], prefix); ok {
				configPath = value
			}
		}
	}
	return configPath
}
